// GENERATED by scripts/gen_flutter_tokens.py from design/tokens/colors.css
// — do not edit by hand; re-run the script after re-mirroring design/.

import 'dart:ui';

/// One resolved color palette (light or dark) of the Briefkist design tokens.
class MfColors {
  final Color paper0;
  final Color paper1;
  final Color paper2;
  final Color paper3;
  final Color ink1;
  final Color ink2;
  final Color ink3;
  final Color plum;
  final Color plumStrong;
  final Color plumTint;
  final Color plumContrast;
  final Color surfacePage;
  final Color surfaceCard;
  final Color surfaceHover;
  final Color surfacePressed;
  final Color surfaceInset;
  final Color surfaceOverlay;
  final Color scrim;
  final Color text1;
  final Color text2;
  final Color text3;
  final Color textOnAccent;
  final Color textLink;
  final Color border;
  final Color borderStrong;
  final Color borderAccent;
  final Color accent;
  final Color accentHover;
  final Color accentTint;
  final Color focusRing;
  final Color ok;
  final Color okTint;
  final Color err;
  final Color errTint;
  final Color warn;
  final Color warnTint;
  final Color processing;
  final Color processingTint;

  const MfColors({
    required this.paper0,
    required this.paper1,
    required this.paper2,
    required this.paper3,
    required this.ink1,
    required this.ink2,
    required this.ink3,
    required this.plum,
    required this.plumStrong,
    required this.plumTint,
    required this.plumContrast,
    required this.surfacePage,
    required this.surfaceCard,
    required this.surfaceHover,
    required this.surfacePressed,
    required this.surfaceInset,
    required this.surfaceOverlay,
    required this.scrim,
    required this.text1,
    required this.text2,
    required this.text3,
    required this.textOnAccent,
    required this.textLink,
    required this.border,
    required this.borderStrong,
    required this.borderAccent,
    required this.accent,
    required this.accentHover,
    required this.accentTint,
    required this.focusRing,
    required this.ok,
    required this.okTint,
    required this.err,
    required this.errTint,
    required this.warn,
    required this.warnTint,
    required this.processing,
    required this.processingTint,
  });
}

const mfLight = MfColors(
  paper0: Color(0xFFF6F3ED),
  paper1: Color(0xFFFDFCF9),
  paper2: Color(0xFFF0ECE5),
  paper3: Color(0xFFE7E3DB),
  ink1: Color(0xFF272229),
  ink2: Color(0xFF5C555D),
  ink3: Color(0xFF837E85),
  plum: Color(0xFF7C4F86),
  plumStrong: Color(0xFF683C71),
  plumTint: Color(0xFFF4E8F6),
  plumContrast: Color(0xFFFDFCF9),
  surfacePage: Color(0xFFF6F3ED),
  surfaceCard: Color(0xFFFDFCF9),
  surfaceHover: Color(0xFFF0ECE5),
  surfacePressed: Color(0xFFE7E3DB),
  surfaceInset: Color(0xFFF0ECE5),
  surfaceOverlay: Color(0xFFFDFCF9),
  scrim: Color(0x66272229),
  text1: Color(0xFF272229),
  text2: Color(0xFF5C555D),
  text3: Color(0xFF837E85),
  textOnAccent: Color(0xFFFDFCF9),
  textLink: Color(0xFF7C4F86),
  border: Color(0xFFDDD9D0),
  borderStrong: Color(0xFFBFBAB1),
  borderAccent: Color(0xFF7C4F86),
  accent: Color(0xFF7C4F86),
  accentHover: Color(0xFF683C71),
  accentTint: Color(0xFFF4E8F6),
  focusRing: Color(0xFF7C4F86),
  ok: Color(0xFF33724C),
  okTint: Color(0xFFE0F2E6),
  err: Color(0xFF9C433F),
  errTint: Color(0xFFFAE8E6),
  warn: Color(0xFF936831),
  warnTint: Color(0xFFF8EDD8),
  processing: Color(0xFF7C4F86),
  processingTint: Color(0xFFF4E8F6),
);

const mfDark = MfColors(
  paper0: Color(0xFF1A151B),
  paper1: Color(0xFF231E24),
  paper2: Color(0xFF2F2930),
  paper3: Color(0xFF373239),
  ink1: Color(0xFFEAE7E2),
  ink2: Color(0xFFAEAAA4),
  ink3: Color(0xFF837E85),
  plum: Color(0xFFC39ACC),
  plumStrong: Color(0xFFD5ADDE),
  plumTint: Color(0xFF3C2840),
  plumContrast: Color(0xFF191419),
  surfacePage: Color(0xFF1A151B),
  surfaceCard: Color(0xFF231E24),
  surfaceHover: Color(0xFF2F2930),
  surfacePressed: Color(0xFF373239),
  surfaceInset: Color(0xFF2F2930),
  surfaceOverlay: Color(0xFF231E24),
  scrim: Color(0x8C070508),
  text1: Color(0xFFEAE7E2),
  text2: Color(0xFFAEAAA4),
  text3: Color(0xFF837E85),
  textOnAccent: Color(0xFF191419),
  textLink: Color(0xFFC39ACC),
  border: Color(0xFF39333A),
  borderStrong: Color(0xFF565057),
  borderAccent: Color(0xFFC39ACC),
  accent: Color(0xFFC39ACC),
  accentHover: Color(0xFFD5ADDE),
  accentTint: Color(0xFF3C2840),
  focusRing: Color(0xFFC39ACC),
  ok: Color(0xFF75B68C),
  okTint: Color(0xFF1D3425),
  err: Color(0xFFE18881),
  errTint: Color(0xFF402624),
  warn: Color(0xFFD3A96F),
  warnTint: Color(0xFF3C2D18),
  processing: Color(0xFFC39ACC),
  processingTint: Color(0xFF3C2840),
);
