"""Generate app/lib/design/tokens.g.dart from design/tokens/colors.css.

The design system (design/, mirrored from Claude Design) specifies colors as
oklch(); Flutter has no oklch, so this script converts every token to sRGB
deterministically (CSS Color 4 reference math) and emits a Dart file with the
light (:root) and dark ([data-theme="dark"]) palettes. Re-run after re-mirroring
the design:

    uv run python scripts/gen_flutter_tokens.py
"""

from __future__ import annotations

import math
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSS = REPO / "design" / "tokens" / "colors.css"
OUT = REPO / "app" / "lib" / "design" / "tokens.g.dart"


def oklch_to_srgb8(lightness: float, chroma: float, hue_deg: float) -> tuple[int, int, int]:
    """oklch -> sRGB 0-255, CSS Color 4 reference conversion (clamped)."""
    hue = math.radians(hue_deg)
    a = chroma * math.cos(hue)
    b = chroma * math.sin(hue)
    # oklab -> LMS (cube roots undone)
    l_ = lightness + 0.3963377774 * a + 0.2158037573 * b
    m_ = lightness - 0.1055613458 * a - 0.0638541728 * b
    s_ = lightness - 0.0894841775 * a - 1.2914855480 * b
    lin = (l_**3, m_**3, s_**3)
    r = +4.0767416621 * lin[0] - 3.3077115913 * lin[1] + 0.2309699292 * lin[2]
    g = -1.2684380046 * lin[0] + 2.6097574011 * lin[1] - 0.3413193965 * lin[2]
    bl = -0.0041960863 * lin[0] - 0.7034186147 * lin[1] + 1.7076147010 * lin[2]

    def gamma(c: float) -> int:
        c = max(0.0, min(1.0, c))
        c = 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055
        return round(max(0.0, min(1.0, c)) * 255)

    return gamma(r), gamma(g), gamma(bl)


OKLCH_RE = re.compile(r"oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:/\s*([\d.]+))?\s*\)")
DECL_RE = re.compile(r"--([\w-]+)\s*:\s*([^;]+);")
VAR_RE = re.compile(r"var\(--([\w-]+)\)")


def parse_block(css: str, selector: str) -> dict[str, str]:
    """Return {token: raw-value} for the rule whose selector opens a line.

    Matching at line start keeps prose mentions of the selector (e.g. the
    header comment naming `[data-theme="dark"]`) from being mistaken for the
    rule itself.
    """
    m = re.search(rf"^{re.escape(selector)}\s*{{", css, re.MULTILINE)
    if not m:
        raise ValueError(f"selector not found: {selector}")
    body = css[m.end() : css.index("}", m.end())]
    return {d.group(1): d.group(2).strip() for d in DECL_RE.finditer(body)}


def resolve(tokens: dict[str, str]) -> dict[str, tuple[int, int, int, int]]:
    """Resolve var() refs and oklch() to (r, g, b, a255)."""
    out: dict[str, tuple[int, int, int, int]] = {}

    def value_of(name: str, seen: frozenset[str] = frozenset()) -> tuple[int, int, int, int]:
        if name in out:
            return out[name]
        if name in seen:
            raise ValueError(f"var() cycle at --{name}")
        raw = tokens[name]
        ref = VAR_RE.fullmatch(raw)
        if ref:
            rgba = value_of(ref.group(1), seen | {name})
        else:
            m = OKLCH_RE.fullmatch(raw)
            if not m:
                raise ValueError(f"unparseable token --{name}: {raw}")
            r, g, b = oklch_to_srgb8(float(m[1]), float(m[2]), float(m[3]))
            alpha = round(float(m[4]) * 255) if m[4] else 255
            rgba = (r, g, b, alpha)
        out[name] = rgba
        return rgba

    for name in tokens:
        value_of(name)
    return out


def dart_name(token: str) -> str:
    parts = token.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def dart_color(rgba: tuple[int, int, int, int]) -> str:
    r, g, b, a = rgba
    return f"Color(0x{a:02X}{r:02X}{g:02X}{b:02X})"


def main() -> None:
    css = CSS.read_text()
    light_raw = parse_block(css, ":root")
    dark_block = parse_block(css, '[data-theme="dark"]')
    # dark inherits every light token it doesn't override
    dark_raw = {**light_raw, **dark_block}

    light = resolve(light_raw)
    dark = resolve(dark_raw)
    assert light.keys() == dark.keys()

    lines = [
        "// GENERATED by scripts/gen_flutter_tokens.py from design/tokens/colors.css",
        "// — do not edit by hand; re-run the script after re-mirroring design/.",
        "",
        "import 'dart:ui';",
        "",
        "/// One resolved color palette (light or dark) of the my-flopy design tokens.",
        "class MfColors {",
    ]
    names = list(light.keys())
    lines += [f"  final Color {dart_name(n)};" for n in names]
    lines.append("")
    lines.append("  const MfColors({")
    lines += [f"    required this.{dart_name(n)}," for n in names]
    lines.append("  });")
    lines.append("}")
    lines.append("")
    for label, palette in (("light", light), ("dark", dark)):
        lines.append(f"const mf{label.capitalize()} = MfColors(")
        lines += [f"  {dart_name(n)}: {dart_color(palette[n])}," for n in names]
        lines.append(");")
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)} ({len(names)} tokens x light+dark)")


if __name__ == "__main__":
    main()
