import React from "react";

/* my-flopy — shared sample data for UI kits. Archive content only: no amounts, no due dates. */

export const CATEGORIES = ["government","medical","insurance","bank","utility","telecom","legal","employment","education","housing","commercial","membership","personal","other"];

export const DOCS = [
  {
    id: 1,
    title: "Wijziging zorgverzekering 2026",
    correspondent: "Zilveren Kruis", place: "Leusden",
    recipient: "J. van der Berg",
    date: "12 Mar 2026", category: "insurance",
    reference: "ZK-2026-118-P", language: "Dutch",
    subject: "Policy change effective 1 January 2026",
    summary: "Zilveren Kruis confirms the requested change to the basic health-insurance policy, effective 1 January 2026. The dental add-on is discontinued and the physiotherapy add-on continues unchanged. A revised policy schedule is enclosed as page two.",
    keywords: ["zorgverzekering","polis 2026","aanvullende verzekering","fysiotherapie"],
    pages: 2, status: "done",
  },
  {
    id: 2,
    title: "Jaaropgave 2025",
    correspondent: "Belastingdienst", place: "Apeldoorn",
    recipient: "J. van der Berg",
    date: "28 Jan 2026", category: "government",
    reference: "JO-2025-8841", language: "Dutch",
    subject: "Annual statement 2025",
    summary: "The annual statement for 2025 as registered with the tax administration. Keep this document for your records; it is used when filing the income-tax return.",
    keywords: ["jaaropgave","2025","inkomstenbelasting"],
    pages: 1, status: "done",
  },
  {
    id: 3,
    title: "Afspraakbevestiging cardiologie",
    correspondent: "UMC Utrecht", place: "Utrecht",
    recipient: "J. van der Berg",
    date: "3 Jun 2026", category: "medical",
    reference: "POLI-C-26-0331", language: "Dutch",
    subject: "Appointment confirmation, cardiology outpatient clinic",
    summary: "Confirmation of an appointment at the cardiology outpatient clinic. The letter lists the preparation instructions and asks you to bring a current medication list.",
    keywords: ["afspraak","cardiologie","polikliniek"],
    pages: 1, status: "done",
  },
  {
    id: 4,
    title: "Terminbestätigung Zulassungsstelle",
    correspondent: "Stadt Köln", place: "Köln",
    recipient: "J. van der Berg",
    date: "14 May 2026", category: "government",
    reference: "KFZ-2026-77102", language: "German",
    subject: "Vehicle registration appointment",
    summary: "Die Zulassungsstelle bestätigt den Termin zur Fahrzeugummeldung. Mitzubringen sind Personalausweis, Fahrzeugschein und der Nachweis der Versicherung (eVB-Nummer).",
    keywords: ["Zulassung","Fahrzeug","Termin"],
    pages: 1, status: "done",
  },
  {
    id: 5,
    title: "Bevestiging contractverlenging internet",
    correspondent: "Ziggo", place: "Utrecht",
    recipient: "J. van der Berg",
    date: "22 Apr 2026", category: "telecom",
    reference: "ZG-4471-2026", language: "Dutch",
    subject: "Contract renewal confirmation",
    summary: "Ziggo bevestigt de verlenging van het internetabonnement voor twaalf maanden. De huidige snelheid en modemconfiguratie blijven ongewijzigd.",
    keywords: ["contract","internet","verlenging"],
    pages: 1, status: "done",
  },
  {
    id: 6,
    title: "Statement of employment",
    correspondent: "Acme B.V.", place: "Amsterdam",
    recipient: "J. van der Berg",
    date: "9 Feb 2026", category: "employment",
    reference: "HR-2026-014", language: "English",
    subject: "Employer's statement for housing application",
    summary: "Acme B.V. confirms the current employment relationship and position for use in a housing application. The statement is signed by the head of human resources.",
    keywords: ["werkgeversverklaring","employment","housing application"],
    pages: 1, status: "done",
  },
  {
    id: 7,
    title: "Servicekosten afrekening 2025",
    correspondent: "VvE De Linde", place: "Utrecht",
    recipient: "J. van der Berg",
    date: "30 Mar 2026", category: "housing",
    reference: "VVE-SK-2025", language: "Dutch",
    subject: "Service-charge settlement 2025",
    summary: "De vereniging van eigenaars stuurt de jaarlijkse afrekening van de servicekosten over 2025, vastgesteld in de algemene ledenvergadering van maart.",
    keywords: ["VvE","servicekosten","afrekening"],
    pages: 2, status: "done",
  },
];

export const UPLOADS = [
  { id: 101, title: null, status: "processing", statusLabel: "Reading page 1 of 2…", time: "just now" },
  { id: 102, title: null, status: "queued", statusLabel: "Queued", time: "1 min ago" },
  { id: 103, title: "Afspraakbevestiging cardiologie", status: "done", statusLabel: "Filed · medical", time: "8 min ago" },
  { id: 104, title: null, status: "error", statusLabel: "Couldn't read page 2", time: "12 min ago" },
];
